import NavigationFoodMenu from "@/components/publiCcomponents/foodMenu/NavigationFoodMenu"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <div className=" flex flex-col w-full h-screen justify-between dark:bg-zinc-900 dark:text-zinc-100">
      <div className=" flex-1">
        {children}
      </div>
      <ul
        className='h-20 flex justify-start items-center overflow-x-auto bg-slate-400'>
        <NavigationFoodMenu />
      </ul>
    </div>
  )
}
