import BodyFoodMenu from "@/components/publiCcomponents/foodMenu/BodyFoodMenu"
// import FoodMenu from "@/components/publiCcomponents/foodMenu/FoodMenu"
// import NavigationFoodMenu from "@/components/publiCcomponents/foodMenu/NavigationFoodMenu"
// import { CAT } from "@/type"
import axios from "axios"
import queryString from "query-string"

export const metadata = {
    title: 'Food Menu',
    description: 'Generated by Mohsen Shahrokhi',
}

async function getData(searchParams: any) {

    const theme = searchParams.theme

    delete searchParams.theme

    const stringified = queryString.stringify(searchParams)

    const p = await axios.get(`${process.env.BASE_URL}/api/product?${stringified}`)

    return { products: p.data.products }
}

export default async function MenuPage({ searchParams }: { searchParams: { [key: string]: string | string[] | undefined } }) {

    const { products } = await getData(searchParams)

    return (
        <div className="flex-1">
            <BodyFoodMenu products={products} />
        </div>
    )
}
